import tkinter
from tkinter import ttk
root = tkinter.Tk()
root.title("OneUI Debloater")
img = tkinter.PhotoImage(file='bannerpng.png')
tkinter.Label(
    root,
    image=img
).pack()

##Uninstallers
#Definiting what should be uninsstalled
arzone = tkinter.StringVar()
ardrawing = tkinter.StringVar()
visionarapps = tkinter.StringVar()
#bixpypack = Bixby,Bixby Vision,Bixby Voice,Bixby Vision Framework
bixbypack = tkinter.StringVar()
bookmarkprovider = tkinter.StringVar()
briefing = tkinter.StringVar()
chrome = tkinter.StringVar()
deco_pic=tkinter.StringVar()
dexonpc = tkinter.StringVar()
devicehealthservices = tkinter.StringVar()
duo = tkinter.StringVar()
facebook = tkinter.StringVar()
#Galaxy Pack = Galaxy Themes, Wearable
galaxypack = tkinter.StringVar()
gameboster = tkinter.StringVar()
gamelauncher=tkinter.StringVar()
gameoptimizingservice=tkinter.StringVar()
gmail = tkinter.StringVar()
google = tkinter.StringVar()
playservicesar = tkinter.StringVar()
googleplayvideos = tkinter.StringVar()
googleassistant = tkinter.StringVar()
googlephotos = tkinter.StringVar()
healthservice = tkinter.StringVar()
linksharing = tkinter.StringVar()
office = tkinter.StringVar()
onedrive = tkinter.StringVar()
outlook = tkinter.StringVar()
privateshare = tkinter.StringVar()
daily = tkinter.StringVar()
dex = tkinter.StringVar()
galaxynofreinds = tkinter.StringVar() # ;)
globalgoals = tkinter.StringVar()
health = tkinter.StringVar()
internet = tkinter.StringVar()
kids = tkinter.StringVar()
spass = tkinter.StringVar()
passprovider = tkinter.StringVar()
pay = tkinter.StringVar()
suckingfolder = tkinter.StringVar() # :)
dumbthings = tkinter.StringVar()
smarttutor = tkinter.StringVar()
frickkey = tkinter.StringVar()
wearablemanager = tkinter.StringVar()
youtube = tkinter.StringVar()
passautofill = tkinter.StringVar()
bixbywakeup = tkinter.StringVar()
dexlauncher=tkinter.StringVar()
googledocs=tkinter.StringVar()


ttk.Checkbutton(root,text="Ar Zone",variable=arzone,onvalue='1',offvalue='0').pack()
root.mainloop()